name: Build Cordova Android

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. إعداد Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. إعداد Java 17 (Temurin)
      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. تثبيت الحزم المساعدة
      - name: Install helper packages
        run: sudo apt-get update && sudo apt-get install -y wget unzip

      # 5. تثبيت أدوات الأندرويد و SDK
      - name: Install Android command-line tools & SDK packages
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest || true
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      # 6. إضافة SDK إلى PATH
      - name: Expose Android SDK to PATH and env
        run: |
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      # 7. تثبيت Cordova واعتماديات المشروع
      - name: Install project dependencies & Cordova
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm install
          fi
          npm install -g cordova

      # 8. إعداد منصة Android
      - name: Prepare Cordova Android platform
        run: |
          cordova telemetry off || true
          cordova platform rm android || true
          cordova platform add android@latest --save

      # 9. بناء APK و AAB معًا
      - name: Build Android (APK & AAB)
        run: |
          cordova build android --release --no-telemetry --packageType=apk
          cordova build android --release --no-telemetry --packageType=bundle

      # 10. عرض جميع الملفات المخرجة (للتأكد)
      - name: Check all outputs
        run: find platforms/android/app/build/outputs -type f

      # 11. رفع APK و AAB كـ artifacts
      - name: Upload APK & AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyWeatherApp-builds
          path: |
            platforms/android/app/build/outputs/apk/release/*.apk
            platforms/android/app/build/outputs/bundle/release/*.aab
